server:
  port: 8291
spring:
  application:
    name: SERVICE-AUTH
  redis:
    host: 172.16.10.43
    port: 6379
    database: 0
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8260/eureka
    instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 3