server:
  port: 8271
spring:
  application:
    name: SERVICE-PROVIDER
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8260/eureka
    instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 3