server:
  port: 8250
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8260/eureka
    instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 3
spring:
  application:
    name: SERVICE-GATEWAY
  cloud:
    gateway:
      locator:
        enabled: true
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
        - id: path_route
          uri: http://localhost:8281
          order: 100
          predicates:
            - Path=/**
        - id: auth_route
          uri: http://localhost:8291
          order: 0
          predicates:
            - Path=/oauth/**
        - id: auth_principle_route
          uri: http://localhost:8291
          order: 0
          predicates:
            - Path=/getPrinciple
        - id: order_route
          uri: http://localhost:8292
          order: 0
          predicates:
            - Path=/order/**
        - id: product_route
          uri: http://localhost:8292
          order: 0
          predicates:
            - Path=/product/**
        - id: route_security
          uri: http://localhost:8293
          order: 2
          predicates:
            - Path=/security/**
          filters:
            - PreserveHostHeader
        - id: route_security_2
          uri: http://localhost:8293
          order: 0
          predicates:
            - Path=/security/hi
          filters:
            - SaveSession
            - PreserveHostHeader