server:
  port: 8250
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8281
          order: 0
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0