server:
  port: 8250
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8260/eureka
    instance:
      lease-expiration-duration-in-seconds: 6
      lease-renewal-interval-in-seconds: 3
spring:
  application:
    name: SERVICE-GATEWAY
  cloud:
    gateway:
      locator:
        enabled: true
      default-filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
        - id: path_route
          uri: http://localhost:8281
          order: 0
          predicates:
            - Path=/**